### PR TITLE
Wl 3711

### PR DESCRIPTION
**Pull request by ouit0408**
Improved the "Remove Site" message/screen

### CODE REVIEW

**Comment by buckett** [comment]
Your commit currently has all the IntelliJ project files in it. You should drop these files out of the commits.

Also it's normal to prefix all your commits with the Jira reference WL-3711 so that when someone does a `git blame` they can easily find out why the changes were made.

**Comment by ouit0408** [comment]
I have added .gitignore file in my project to ignore IntelliJ files from future commits.

Next time will not miss prefixing my commits with Jira reference, point noted.
________________________________

**Comment by buckett** [comment]
On 7 July 2015 at 16:10, ouit0408 <notifications@github.com> wrote:

> I have added .gitignore file in my project to ignore IntelliJ files from
> future commits.
>
> Next time will not miss prefixing my commits with Jira reference, point
> noted.
>

It's worth doing this in your global .gitignore so that if you have a copy
of Sakai 11 as well you don't end up with your IntelliJ files in there as
well.
https://help.github.com/articles/ignoring-files/#create-a-global-gitignore


-- 
  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by ouit0408** [comment]
Rebased the previous commit and removed IntelliJ files , ready to pull.

**Comment by buckett** [comment]
How is the user supposed to leave the remove site screen without the cancel button?

**Comment by ouit0408** [comment]
Added the "Cancel" button back.

**Comment by buckett** [comment]
You don't have to fix it but watch out for indentation (tabs/space) on any files you edit. You should always try to match the existing indentation on a file.

**Pull request merged**
